name: Run Test Suites

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  RunUnitTests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-spec pytest-describe

      - name: Run Pytest
        run: pytest --spec --color=yes test_battery.py

  RunUITests:
    name: Run UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Chromedriver
        uses: nanasess/setup-chromedriver@master

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave behave-webdriver

      - name: Run Behave Tests
        run: behave features/HeronsCalculator.feature